# Generated by Django 5.0.6 on 2024-10-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_usermodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('location_image', models.ImageField(upload_to='hotels/location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('out_image', models.ImageField(upload_to='hotels/out_images/')),
                ('in_image1', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('in_image2', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('in_image3', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('in_image4', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('in_image5', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('in_image6', models.ImageField(blank=True, null=True, upload_to='hotels/in_images/')),
                ('sub_location', models.CharField(max_length=100)),
                ('distance', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=5)),
                ('main_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotels.locationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hotels.hotelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='hotels/room_images/')),
                ('room_no', models.IntegerField(default=0)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=10)),
                ('price', models.IntegerField(default=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotels.hotelmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('NID_number', models.CharField(max_length=20)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.usermodel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotels.hotelmodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotels.roommodel')),
            ],
        ),
    ]
