# Generated by Django 5.0.6 on 2024-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
